In [1]:
# Imports

import pandas as pd
pd.set_option('max_columns', 30)
from datetime import datetime
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
sns.set(style='whitegrid', context='talk', palette='bright', color_codes=True)

## Adidas

In [2]:
df_adidas = pd.read_pickle("./Pickles/df_official_adidas_tweets.pkl")

In [3]:
df_adidas

,cashtags,conversation_id,created_at,date,day,geo,hashtags,hour,id,link,name,near,nlikes,nreplies,nretweets,place,quote_url,reply_to,retweet,retweet_date,retweet_id,search,source,timezone,tweet,user_id,user_id_str,user_rt,user_rt_id,username
0,[],1179119534772559873,1569958978000,2019-10-01 15:42:58,1,,[#heretocreate],07,1179119534772559873,https://twitter.com/adidas/status/117911953477...,adidas,,496,35,67,,,"[{'user_id': '300114634', 'username': 'adidas'}]",False,,,None,,EDT,Noah Lyles used to spend his time sketching hi...,300114634,300114634,,,adidas
1,[],1177931059629101062,1569675624000,2019-09-28 09:00:24,4,,[#heretocreate],17,1177931059629101062,https://twitter.com/adidas/status/117793105962...,adidas,,260,17,42,,,"[{'user_id': '300114634', 'username': 'adidas'}]",False,,,None,,EDT,From the training grounds in Kenya to the stre...,300114634,300114634,,,adidas
2,[],1156977288291999744,1567692152000,2019-09-05 10:02:32,7,,[],22,1169611776880721920,https://twitter.com/adidas/status/116961177688...,adidas,,187,47,25,,,"[{'user_id': '300114634', 'username': 'adidas'...",False,,,None,,EDT,Running With @Dele_Official ​ One of football...,300114634,300114634,,,adidas
3,[],1161191675009490945,1567528439000,2019-09-03 12:33:59,3,,[#yesadidas],01,1168925115444281344,https://twitter.com/adidas/status/116892511544...,adidas,,0,0,0,,,"[{'user_id': '300114634', 'username': 'adidas'...",False,,,None,,EDT,We’d love to share this photo with the adidas ...,300114634,300114634,,,adidas
4,[],1156977288291999744,1567087823000,2019-08-29 10:10:23,6,,[],08,1167077035581165568,https://twitter.com/adidas/status/116707703558...,adidas,,1457,66,117,,,"[{'user_id': '300114634', 'username': 'adidas'...",False,,,None,,EDT,"In the next episode of Running With, @TeamJuJu...",300114634,300114634,,,adidas
5,[],1163053564559650817,1566129277000,2019-08-18 07:54:37,7,,[],02,1163056604008202241,https://twitter.com/adidas/status/116305660400...,adidas,,294,48,37,,,"[{'user_id': '300114634', 'username': 'adidas'}]",False,,,None,,EDT,Each product represents a moment in our histor...,300114634,300114634,,,adidas
6,[],1163053564559650817,1566129276000,2019-08-18 07:54:36,7,,[],02,1163056600069730305,https://twitter.com/adidas/status/116305660006...,adidas,,444,48,60,,,"[{'user_id': '300114634', 'username': 'adidas'}]",False,,,None,,EDT,"2017, Futurecraft 4D​ ​ With increased awarene...",300114634,300114634,,,adidas
7,[],1163053564559650817,1566129274000,2019-08-18 07:54:34,7,,[],01,1163056592327045121,https://twitter.com/adidas/status/116305659232...,adidas,,219,32,32,,,"[{'user_id': '300114634', 'username': 'adidas'...",False,,,None,,EDT,"2016, adidas x Parley ​ ​ Sustainability has b...",300114634,300114634,,,adidas
8,[],1163053564559650817,1566129272000,2019-08-18 07:54:32,7,,[],00,1163056584605327360,https://twitter.com/adidas/status/116305658460...,adidas,,197,8,20,,,"[{'user_id': '300114634', 'username': 'adidas'}]",False,,,None,,EDT,"2015, NMD R1 Primeknit​ ​ NMD stands for nomad...",300114634,300114634,,,adidas
9,[],1163053564559650817,1566129270000,2019-08-18 07:54:30,7,,[],00,1163056575772127233,https://twitter.com/adidas/status/116305657577...,adidas,,111,5,16,,,"[{'user_id': '300114634', 'username': 'adidas'}]",False,,,None,,EDT,"2013, Energy Boost ​ ​ Running changed forever...",300114634,300114634,,,adidas
10,[],1163053564559650817,1566129269000,2019-08-18 07:54:29,7,,[],00,1163056568750899200,https://twitter.com/adidas/status/116305656875...,adidas,,91,5,24,,,"[{'user_id': '300114634', 'username': 'adidas'}]",False,,,None,,EDT,"2002, YY Mei Brocade ​ ​ The 2000’s were a dec...",300114634,300114634,,,adidas
11,[],1163053564559650817,1566129267000,2019-08-18 07:54:27,6,,[],23,1163056560563613699,https://twitter.com/adidas/status/116305656056...,adidas,,110,7,18,,,"[{'user_id': '300114634', 'username': 'adidas'}]",False,,,None,,EDT,"1994, Predator Cup ​ ​ The ‘90s was a period o...",300114634,300114634,,,adidas
12,[],1163053564559650817,1566129265000,2019-08-18 07:54:25,6,,[],22,1163056552976105472,https://twitter.com/adidas/status/116305655297...,adidas,,103,3,17,,,"[{'user_id': '300114634', 'username': 'adidas'}]",False,,,None,,EDT,"1988, M45K BEST​ ​ The '80s was a decade for i...",300114634,300114634,,,adidas
13,[],1163053564559650817,1566129263000,2019-08-18 07:54:23,6,,[],22,1163056543987748865,https://twitter.com/adidas/status/116305654398...,adidas,,162,1,24,,,"[{'user_id': '300114634', 'username': 'adidas'...",False,,,None,,EDT,"1970, TELSTAR​ ​ TELSTAR (“star of television”...",300114634,300114634,,,adidas
14,[],1163053564559650817,1566128564000,2019-08-18 07:42:44,5,,[],20,1163053613343633409,https://twitter.com/adidas/status/116305361334...,adidas,,159,4,27,,,"[{'user_id': '300114634', 'username': 'adidas'...",False,,,None,,EDT,"1973, Stan Smith​ ​ The '70s laid the foundati...",300114634,300114634,,,adidas
15,[],1163053564559650817,1566128563000,2019-08-18 07:42:43,5,,[],19,1163053606892797953,https://twitter.com/adidas/status/116305360689...,adidas,,128,4,26,,,"[{'user_id': '300114634', 'username': 'adidas'}]",False,,,None,,EDT,"1970, Superstar​ ​ The ‘70s brought iconic mus...",300114634,300114634,,,adidas
16,[],1163053564559650817,1566128561000,2019-08-18 07:42:41,5,,[],19,1163053599603093505,https://twitter.com/adidas/status/116305359960...,adidas,,140,2,20,,,"[{'user_id': '300114634', 'username': 'adidas'}]",False,,,None,,EDT,"1967, Franz Beckenbauer​ ​ When the tracksuit ...",300114634,300114634,,,adidas
17,[],1163053564559650817,1566128559000,2019-08-18 07:42:39,5,,[],18,1163053591436726272,https://twitter.com/adidas/status/116305359143...,adidas,,144,3,23,,,"[{'user_id': '300114634', 'username': 'adidas'}]",False,,,None,,EDT,"1965, Gazelle​ ​ This was the decade for athle...",300114634,300114634,,,adidas
18,[],1163053564559650817,1566128557000,2019-08-18 07:42:37,5,,[],18,1163053582876172288,https://twitter.com/adidas/status/116305358287...,adidas,,127,26,26,,,"[{'user_id': '300114634', 'username': 'adidas'}]",False,,,None,,EDT,"1953, Argentinia​ ​ Who would have thought tha...",300114634,300114634,,,adidas
19,[],1163053564559650817,1566128555000,2019-08-18 07:42:35,5,,[],17,1163053574697279489,https://twitter.com/adidas/status/116305357469...,adidas,,139,20,28,,,"[{'user_id': '300114634', 'username': 'adidas'}]",False,,,None,,EDT,"1950, Samba​ ​ The ‘50s became a boom of techn...",300114634,300114634,,,adidas
20,[],1163053564559650817,1566128553000,2019-08-18 07:42:33,5,,[],17,1163053567000772608,https://twitter.com/adidas/status/116305356700...,adidas,,83,3,10,,,"[{'user_id': '300114634', 'username': 'adidas'}]",False,,,None,,EDT,Scroll through our history & discover the styl...,300114634,300114634,,,adidas
21,[],1163053564559650817,1566128553000,2019-08-18 07:42:33,5,,[],17,1163053565956378626,https://twitter.com/adidas/status/116305356595...,adidas,,102,4,19,,,"[{'user_id': '300114634', 'username': 'adidas'}]",False,,,None,,EDT,"Since then, we have done our best for the best...",300114634,300114634,,,adidas
22,[],1163053564559650817,1566128552000,2019-08-18 07:42:32,5,,[],16,1163053564559650817,https://twitter.com/adidas/status/116305356455...,adidas,,1274,124,341,,,"[{'user_id': '300114634', 'username': 'adidas'}]",False,,,None,,EDT,"On this day in 1949, Adi Dassler registered th...",300114634,300114634,,,adidas
23,[],1161261946693283840,1565701397000,2019-08-13 09:03:17,3,,[#heretocreate],17,1161261946693283840,https://twitter.com/adidas/status/116126194669...,adidas,,896,32,130,,,"[{'user_id': '300114634', 'username': 'adidas'...",False,,,None,,EDT,See where your curiosity can take you. Welcom...,300114634,300114634,,,adidas
24,[],1156977288291999744,1565619299000,2019-08-12 10:14:59,5,,[],13,1160917602643763201,https://twitter.com/adidas/status/116091760264...,adidas,,368,9,54,,,"[{'user_id': '300114634', 'username': 'adidas'...",False,,,None,,EDT,"Running With @karliekloss Supermodel, Coding...",300114634,300114634,,,adidas
25,[],1156977288291999744,1564679855000,2019-08-01 13:17:35,3,,[],09,1156977288291999744,https://twitter.com/adidas/status/115697728829...,adidas,,695,45,80,,,"[{'user_id': '300114634', 'username': 'adidas'...",False,,,None,,EDT,Running With @PUSHA_T ​ From mics to miles. K...,300114634,300114634,,,adidas
26,[],1153341787542564866,1563813084000,2019-07-22 12:31:24,2,,[],07,1153341787542564866,https://twitter.com/adidas/status/115334178754...,adidas,,379,46,46,,,"[{'user_id': '300114634', 'username': 'adidas'...",False,,,None,,EDT,"Hear from names across entertainment, sport an...",300114634,300114634,,,adidas
27,[],1151161107450662914,1563293170000,2019-07-16 12:06:10,4,,[],18,1151161107450662914,https://twitter.com/adidas/status/115116110745...,adidas,,2511,284,396,,,"[{'user_id': '300114634', 'username': 'adidas'}]",False,,,None,,EDT,Boost. We made it a game-changer. You made it ...,300114634,300114634,,,adidas
28,[],1147912272171405312,1562518587000,2019-07-07 12:56:27,6,,"[#fifawwc, #daretocreate]",16,1147912272171405312,https://twitter.com/adidas/status/114791227217...,adidas,,578,57,97,,,"[{'user_id': '300114634', 'username': 'adidas'...",False,,,None,,EDT,Dare to be the best in the world. Then do it a...,300114634,300114634,,,adidas
29,[],1141534733840650240,1560998063000,2019-06-19 22:34:23,6,,[#heretocreate],00,1141534733840650240,https://twitter.com/adidas/status/114153473384...,adidas,,297,191,35,,,"[{'user_id': '300114634', 'username': 'adidas'...",False,,,None,,EDT,"Some find opportunity in their game, others ma...",300114634,300114634,,,adidas
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11920,[],72763846074437632,1306229336000,2011-05-24 05:28:56,1,,[],22,72957239538892800,https://twitter.com/adidas/status/729572395388...,adidas,,0,0,0,,,"[{'user_id': '300114634', 'username': 'adidas'...",False,,,None,,EDT,@richsumnall @OfficialSCFC We hope you like them!,300114634,300114634,,,adidas
11921,[],72847311461564417,1306229271000,2011-05-24 05:27:51,1,,[],04,72956968880447488,https://twitter.com/adidas/status/729569688804...,adidas,,0,0,0,,,"[{'user_id': '300114634', 'username': 'adidas'}]",False,,,None,,EDT,@OctobersJayLee and we are very proud of our C...,300114634,300114634,,,adidas
11922,[],72865131125678080,1306229239000,2011-05-24 05:27:19,7,,[],19,72956835191205888,https://twitter.com/adidas/status/729568351912...,adidas,,0,0,0,,,"[{'user_id': '300114634', 'username': 'adidas'...",False,,,None,,EDT,@UnCool21 @JColeNC @BigSean How do you like ou...,300114634,300114634,,,adidas
11923,[],72865361036451840,1306229216000,2011-05-24 05:26:56,7,,[],12,72956737619099648,https://twitter.com/adidas/status/729567376190...,adidas,,0,0,0,,,"[{'user_id': '300114634', 'username': 'adidas'...",False,,,None,,EDT,@AtoBoldon We hope you like them! We are very ...,300114634,300114634,,,adidas
11924,[],72866690551136257,1306229194000,2011-05-24 05:26:34,7,,[],06,72956646887931904,https://twitter.com/adidas/status/729566468879...,adidas,,0,0,0,,,"[{'user_id': '300114634', 'username': 'adidas'}]",False,,,None,,EDT,@LOBizDRett Sorry to hear this! We hope you co...,300114634,300114634,,,adidas
11925,[],72421834339004416,1306219336000,2011-05-24 02:42:16,5,,[],04,72915298419867648,https://twitter.com/adidas/status/729152984198...,adidas,,0,0,0,,,"[{'user_id': '300114634', 'username': 'adidas'...",False,,,None,,EDT,@legalmoney We hope you like them :-),300114634,300114634,,,adidas
11926,[],72181420273049600,1306052262000,2011-05-22 04:17:42,3,,[],10,72214538103177216,https://twitter.com/adidas/status/722145381031...,adidas,,0,0,0,,,"[{'user_id': '300114634', 'username': 'adidas'...",False,,,None,,EDT,@LauOnMars they look awesome!,300114634,300114634,,,adidas
11927,[],72001957841219584,1306002072000,2011-05-21 14:21:12,3,,[],13,72004028254523393,https://twitter.com/adidas/status/720040282545...,adidas,,0,0,0,,,"[{'user_id': '300114634', 'username': 'adidas'...",False,,,None,,EDT,@nicolas88batum @realmadrid you are welcome. ...,300114634,300114634,,,adidas
11928,[],71819632683659264,1305963955000,2011-05-21 03:45:55,3,,[],09,71844154375798784,https://twitter.com/adidas/status/718441543757...,adidas,,0,0,0,,,"[{'user_id': '300114634', 'username': 'adidas'}]",False,,,None,,EDT,@Praaveengovind Thanks for the recommendations...,300114634,300114634,,,adidas
11929,[],71550384543514624,1305963875000,2011-05-21 03:44:35,2,,[],11,71843817866792961,https://twitter.com/adidas/status/718438178667...,adidas,,0,0,0,,,"[{'user_id': '300114634', 'username': 'adidas'...",False,,,None,,EDT,@yaz_ahmad Thanks :-),300114634,300114634,,,adidas
11930,[],71795293351444480,1305963603000,2011-05-21 03:40:03,6,,[],07,71842676366000128,https://twitter.com/adidas/status/718426763660...,adidas,,0,0,0,,,"[{'user_id': '300114634', 'username': 'adidas'...",False,,,None,,EDT,@Randalltan and they look awesome.,300114634,300114634,,,adidas
11931,[],71441910006415360,1305870961000,2011-05-20 01:56:01,5,,[],01,71454106488799232,https://twitter.com/adidas/status/714541064887...,adidas,,0,0,0,,,"[{'user_id': '300114634', 'username': 'adidas'}]",False,,,None,,EDT,@Jigstadicta we cannot add anything. Nobody ca...,300114634,300114634,,,adidas
11932,[],71415508909559808,1305870732000,2011-05-20 01:52:12,2,,[],10,71453147758985216,https://twitter.com/adidas/status/714531477589...,adidas,,0,0,0,,,"[{'user_id': '300114634', 'username': 'adidas'...",False,,,None,,EDT,@Jake_Emerson @Kimfinallyhasit what shoes did ...,300114634,300114634,,,adidas
11933,[],71252301129584641,1305829681000,2011-05-19 14:28:01,3,,[],05,71280968354369537,https://twitter.com/adidas/status/712809683543...,adidas,,0,0,0,,,"[{'user_id': '300114634', 'username': 'adidas'...",False,,,None,,EDT,@Jordanlax check our online shop at http://sh...,300114634,300114634,,,adidas
11934,[],71275601666912256,1305828847000,2011-05-19 14:14:07,7,,[],14,71277469625368576,https://twitter.com/adidas/status/712774696253...,adidas,,0,0,0,,,"[{'user_id': '300114634', 'username': 'adidas'}]",False,,,None,,EDT,@xDebbyyyx which one?,300114634,300114634,,,adidas
11935,[],71109895470055424,1305790664000,2011-05-19 03:37:44,6,,[],15,71117316426973184,https://twitter.com/adidas/status/711173164269...,adidas,,0,0,0,,,"[{'user_id': '300114634', 'username': 'adidas'...",False,,,None,,EDT,@Jedao Thanks sharing your love for us :-),300114634,300114634,,,adidas
11936,[],71004888057905152,1305786477000,2011-05-19 02:27:57,7,,[],05,71099755173920769,https://twitter.com/adidas/status/710997551739...,adidas,,0,0,0,,,"[{'user_id': '300114634', 'username': 'adidas'}]",False,,,None,,EDT,@_forestfires Thanks :-),300114634,300114634,,,adidas
11937,[],71003968255442944,1305786419000,2011-05-19 02:26:59,6,,[],13,71099513485541376,https://twitter.com/adidas/status/710995134855...,adidas,,0,0,0,,,"[{'user_id': '300114634', 'username': 'adidas'...",False,,,None,,EDT,@scHarvey we are looking forward for your feed...,300114634,300114634,,,adidas
11938,[],70966009464500226,1305786365000,2011-05-19 02:26:05,5,,[],22,71099287056027648,https://twitter.com/adidas/status/710992870560...,adidas,,0,0,0,,,"[{'user_id': '300114634', 'username': 'adidas'...",False,,,None,,EDT,@imPrettyRicky Congratulations! What are you d...,300114634,300114634,,,adidas
11939,[],71097810384191489,1305786291000,2011-05-19 02:24:51,5,,[],02,71098977709334528,https://twitter.com/adidas/status/710989777093...,adidas,,0,0,0,,,"[{'user_id': '300114634', 'username': 'adidas'...",False,,,None,,EDT,@Ainaamustafa which do you like most?,300114634,300114634,,,adidas
11940,[],71038684060860418,1305781398000,2011-05-19 01:03:18,4,,[],11,71078452618473472,https://twitter.com/adidas/status/710784526184...,adidas,,0,0,0,,,"[{'user_id': '300114634', 'username': 'adidas'}]",False,,,None,,EDT,@FarisGebril we hope so :-),300114634,300114634,,,adidas
11941,[],71075597807394816,1305781317000,2011-05-19 01:01:57,3,,[],12,71078111483138048,https://twitter.com/adidas/status/710781114831...,adidas,,0,0,1,,,"[{'user_id': '300114634', 'username': 'adidas'}]",False,,,None,,EDT,@D1rtyHarrii nice!,300114634,300114634,,,adidas
11942,[],70927894649638912,1305754469000,2011-05-18 17:34:29,7,,[],18,70965504088612866,https://twitter.com/adidas/status/709655040886...,adidas,,0,0,0,,,"[{'user_id': '300114634', 'username': 'adidas'}]",False,,,None,,EDT,@Sebas9PandaQB Agree! That's our thinking ever...,300114634,300114634,,,adidas
11943,[],70634332338921473,1305754172000,2011-05-18 17:29:32,4,,[],08,70964258011230208,https://twitter.com/adidas/status/709642580112...,adidas,,0,0,0,,,"[{'user_id': '300114634', 'username': 'adidas'...",False,,,None,,EDT,@RuthieAlexandra What's stopping you?,300114634,300114634,,,adidas
11944,[],70911267602317312,1305741921000,2011-05-18 14:05:21,2,,[],13,70912873316089857,https://twitter.com/adidas/status/709128733160...,adidas,,0,0,0,,,"[{'user_id': '300114634', 'username': 'adidas'...",False,,,None,,EDT,@Templeatzrv Thanks :-),300114634,300114634,,,adidas
11945,[],70808943517110272,1305741684000,2011-05-18 14:01:24,6,,[],19,70911881287696384,https://twitter.com/adidas/status/709118812876...,adidas,,0,0,0,,,"[{'user_id': '300114634', 'username': 'adidas'}]",False,,,None,,EDT,@SuperKidJunior do you have a photo of them? I...,300114634,300114634,,,adidas
11946,[],70908058448048128,1305741268000,2011-05-18 13:54:28,1,,[],23,70910135157014528,https://twitter.com/adidas/status/709101351570...,adidas,,0,0,1,,,"[{'user_id': '300114634', 'username': 'adidas'...",False,,,None,,EDT,@elmieversx glad to hear this :-),300114634,300114634,,,adidas
11947,[],70796394243428352,1305716516000,2011-05-18 07:01:56,2,,[],12,70806317903777792,https://twitter.com/adidas/status/708063179037...,adidas,,0,0,0,,,"[{'user_id': '300114634', 'username': 'adidas'...",False,,,None,,EDT,@Deetroit_Dave adidas! Of course :-),300114634,300114634,,,adidas
11948,[],70788099659141120,1305712484000,2011-05-18 05:54:44,4,,[],20,70789408458149888,https://twitter.com/adidas/status/707894084581...,adidas,,0,0,0,,,"[{'user_id': '300114634', 'username': 'adidas'...",False,,,None,,EDT,@funnyface8 What shoe were you trying? Do you ...,300114634,300114634,,,adidas
11949,[],70541791715274752,1305712425000,2011-05-18 05:53:45,4,,[],03,70789158502797312,https://twitter.com/adidas/status/707891585027...,adidas,,5,2,1,,,"[{'user_id': '300114634', 'username': 'adidas'...",False,,,None,,EDT,@Persie_Official Thanks a lot!,300114634,300114634,,,adidas

In [4]:
df_adidas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11950 entries, 0 to 11949
Data columns (total 30 columns):
cashtags           11950 non-null object
conversation_id    11950 non-null object
created_at         11950 non-null int64
date               11950 non-null object
day                11950 non-null int64
geo                11950 non-null object
hashtags           11950 non-null object
hour               11950 non-null object
id                 11950 non-null object
link               11950 non-null object
name               11950 non-null object
near               11950 non-null object
nlikes             11950 non-null int64
nreplies           11950 non-null int64
nretweets          11950 non-null int64
place              11950 non-null object
quote_url          11950 non-null object
reply_to           11950 non-null object
retweet            11950 non-null bool
retweet_date       11950 non-null object
retweet_id         11950 non-null object
search             11950 non-null object
source             11950 non-null object
timezone           11950 non-null object
tweet              11950 non-null object
user_id            11950 non-null int64
user_id_str        11950 non-null object
user_rt            11950 non-null object
user_rt_id         11950 non-null object
username           11950 non-null object
dtypes: bool(1), int64(6), object(23)
memory usage: 2.7+ MB

In [5]:
hashtags = []
for hashtag in df_adidas['hashtags'].values.tolist():
    if len(hashtag) != 0:
        hashtags.extend(hashtag)

In [6]:
hashtags_dict = {x: hashtags.count(x) for x in hashtags}

In [7]:
adidas_tag_count = pd.DataFrame.from_dict(hashtags_dict, orient='index', columns=['tag_count'])

In [8]:
adidas_tag_count = adidas_tag_count.sort_values(by=['tag_count'], ascending=False)

In [9]:
adidas_tag_count

                     tag_count
#heretocreate              685
#teamadidas                233
#yesadidas                 147
#adidas                    127
#adidasparley              125
#boost                     101
#allin                      85
#findfocus                  68
#nmd                        65
#ultraboost                 64
#speedtakes                 61
#ebenezersnoop              61
#worldcup                   55
#bahhumbizzle               37
#superstar                  36
#creatorsunite              33
#adidasoriginals            30
#747warehousest             28
#zne                        26
#happyholidizzle            25
#originalis                 22
#eqt                        22
#f50                        17
#goallin                    16
#futurecraft                15
#threestripelife            15
#predatorinstinct           14
#thepulseof                 13
#climachill                 13
#nemeziz                    12
...                        ...
#makes                       1
#adidasteam                  1
#pinkdolphin                 1
#skullboy                    1
#skulls                      1
#allincfc                    1
#prayforboston               1
#needsnotranslation          1
#spezial                     1
#allinrealmadrid             1
#supercup                    1
#forceofblack                1
#allinformurray              1
#barricade                   1
#london                      1
#bikepolo                    1
#moscow2013                  1
#surfsup                     1
#owntheroad                  1
#montecarlomasters           1
#energyrunning               1
#ballondor                   1
#confeds                     1
#mihoney                     1
#adidaseveryday              1
#bigsmiles                   1
#diadelamujer                1
#ace16                       1
#rg13                        1
#facebook                    1

[340 rows x 1 columns]

In [10]:
# df_adidas_best = pd.read_pickle("./Pickles/df_best_adidas_tweets.pkl")

In [11]:
# df_adidas_best

In [12]:
# df_adidas_best.groupby(df_adidas_best['search'])[['tweet']].count()

In [13]:
df_300_adidas_tweets = pd.read_pickle("./Pickles/df_300_adidas_tweets.pkl")

In [14]:
df_300_adidas_tweets.head()

,cashtags,conversation_id,created_at,date,day,geo,hashtags,hour,id,link,name,near,nlikes,nreplies,nretweets,place,quote_url,reply_to,retweet,retweet_date,retweet_id,search,source,timezone,tweet,user_id,user_id_str,user_rt,user_rt_id,username
0,[],1183034711679098880,1570892429000,2019-10-12 11:00:29,4,,"[#footpatrol, #teamfp, #adidas, #pharrellwilli...",04,1183034711679098880,https://twitter.com/Footpatrol_ldn/status/1183...,Footpatrol London,,8,0,0,,,"[{'user_id': '149123728', 'username': 'Footpat...",False,,,Pharrell Williams x Adidas Human Race NMD,,EDT,"adidas Human Race x Human Made NMD Hu, Solar H...",149123728,149123728,,,Footpatrol_ldn
1,[],1182552488811155456,1570777458000,2019-10-11 03:04:18,3,,[],10,1182552488811155456,https://twitter.com/EstelleReed15/status/11825...,Estelle Reed,,0,0,0,,,"[{'user_id': '763132537535287296', 'username':...",False,,,Pharrell Williams x Adidas Human Race NMD,,EDT,Pharrell Williams x Adidas NMD Human Race Trai...,763132537535287296,763132537535287296,,,EstelleReed15
2,[],1181974512985919494,1570639658000,2019-10-09 12:47:38,4,,[],13,1181974512985919494,https://twitter.com/restockuniverse/status/118...,RESTOCK UNIVERSE,,0,0,0,,,"[{'user_id': '1094638704281481216', 'username'...",False,,,Pharrell Williams x Adidas Human Race NMD,,EDT,Adidas PW Human Race NMD Trail x Pharrell Will...,1094638704281481216,1094638704281481216,,,restockuniverse
3,[],1181968365155430403,1570638192000,2019-10-09 12:23:12,1,,[],14,1181968365155430403,https://twitter.com/restockuniverse/status/118...,RESTOCK UNIVERSE,,0,0,0,,,"[{'user_id': '1094638704281481216', 'username'...",False,,,Pharrell Williams x Adidas Human Race NMD,,EDT,Adidas PW Human Race NMD Trail x Pharrell Will...,1094638704281481216,1094638704281481216,,,restockuniverse
4,[],1181968365121888257,1570638192000,2019-10-09 12:23:12,1,,[],14,1181968365121888257,https://twitter.com/restockuniverse/status/118...,RESTOCK UNIVERSE,,0,0,0,,,"[{'user_id': '1094638704281481216', 'username'...",False,,,Pharrell Williams x Adidas Human Race NMD,,EDT,Adidas PW Human Race NMD Trail x Pharrell Will...,1094638704281481216,1094638704281481216,,,restockuniverse

In [15]:
df_327_adidas_tweets = pd.read_pickle("./Pickles/df_327_adidas_tweets.pkl")

In [16]:
df_327_adidas_tweets.head()

,cashtags,conversation_id,created_at,date,day,geo,hashtags,hour,id,link,name,near,nlikes,nreplies,nretweets,place,quote_url,reply_to,retweet,retweet_date,retweet_id,search,source,timezone,tweet,user_id,user_id_str,user_rt,user_rt_id,username
0,[],1184267403137601536,1571186326000,2019-10-15 20:38:46,3,,[#adidas],17,1184267403137601536,https://twitter.com/StockXLive/status/11842674...,StockX Live Feed,,1,0,0,,,"[{'user_id': '761032347403694081', 'username':...",False,,,Adidas Yeezy Boost 700 V2,,EDT,Lowest Ask: $365 adidas Yeezy Boost 700 V2 Van...,761032347403694081,761032347403694081,,,StockXLive
1,[],1184174242608242688,1571164114000,2019-10-15 14:28:34,5,,[],16,1184174242608242688,https://twitter.com/StockXSupply/status/118417...,StockXSupply,,0,0,0,,,"[{'user_id': '1115761929648312320', 'username'...",False,,,Adidas Yeezy Boost 700 V2,,EDT,25% ($75) under retail adidas Yeezy Boost 700 ...,1115761929648312320,1115761929648312320,,,StockXSupply
2,[],1184173464271380481,1571163929000,2019-10-15 14:25:29,3,,[#adidas],12,1184173464271380481,https://twitter.com/StockXLive/status/11841734...,StockX Live Feed,,0,0,0,,,"[{'user_id': '761032347403694081', 'username':...",False,,,Adidas Yeezy Boost 700 V2,,EDT,Lowest Ask: $334 adidas Yeezy Boost 700 V2 Geo...,761032347403694081,761032347403694081,,,StockXLive
3,[],1184111503328337922,1571149156000,2019-10-15 10:19:16,7,,[#adidas],13,1184111503328337922,https://twitter.com/StockXLive/status/11841115...,StockX Live Feed,,0,0,0,,,"[{'user_id': '761032347403694081', 'username':...",False,,,Adidas Yeezy Boost 700 V2,,EDT,Lowest Ask: $290 adidas Yeezy Boost 700 V2 Hos...,761032347403694081,761032347403694081,,,StockXLive
4,[],1184042982749724672,1571132820000,2019-10-15 05:47:00,7,,[#adidas],11,1184042982749724672,https://twitter.com/StockXLive/status/11840429...,StockX Live Feed,,0,0,0,,,"[{'user_id': '761032347403694081', 'username':...",False,,,Adidas Yeezy Boost 700 V2,,EDT,Lowest Ask: $275 adidas Yeezy Boost 700 V2 Geo...,761032347403694081,761032347403694081,,,StockXLive

## Nike

In [17]:
df_nike = pd.read_pickle("./Pickles/df_official_nike_tweets.pkl")

In [18]:
df_nike

,cashtags,conversation_id,created_at,date,day,geo,hashtags,hour,id,link,name,near,nlikes,nreplies,nretweets,place,quote_url,reply_to,retweet,retweet_date,retweet_id,search,source,timezone,tweet,user_id,user_id_str,user_rt,user_rt_id,username
0,[],1181993673464172545,1570645168000,2019-10-09 14:19:28,5,,[],08,1181997624527921153,https://twitter.com/Nike/status/11819976245279...,Nike,,0,0,0,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,"Nothing to share as of now, but keep your eyes...",415859364,415859364,,,Nike
1,[],1181686136764284928,1570577436000,2019-10-08 19:30:36,5,,[],10,1181713534759124992,https://twitter.com/Nike/status/11817135347591...,Nike,,0,0,0,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,Your best bet is to work back with the origina...,415859364,415859364,,,Nike
2,[],1181678486089588736,1570571610000,2019-10-08 17:53:30,7,,[],23,1181689098483961856,https://twitter.com/Nike/status/11816890984839...,Nike,,1,0,0,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,Sounds like it's time for a new pair. 🤙 https:...,415859364,415859364,,,Nike
3,[],1181344921430544384,1570491567000,2019-10-07 19:39:27,5,,[],12,1181353373959938054,https://twitter.com/Nike/status/11813533739599...,Nike,,1,1,0,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,"From start to finish, we'll be along for every...",415859364,415859364,,,Nike
4,[],1181302423048085512,1570482600000,2019-10-07 17:10:00,6,,[],18,1181315764038574084,https://twitter.com/Nike/status/11813157640385...,Nike,,1,1,0,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,"While we don't have a cleaning service, check ...",415859364,415859364,,,Nike
5,[],1180515671966470149,1570312316000,2019-10-05 17:51:56,2,,[],21,1180601540748308483,https://twitter.com/Nike/status/11806015407483...,Nike,,3,0,0,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,Serving up some KMs with a view on the side! 🏃...,415859364,415859364,,,Nike
6,[],1180489298430349313,1570287768000,2019-10-05 11:02:48,5,,[],18,1180498579061968896,https://twitter.com/Nike/status/11804985790619...,Nike,,1,0,0,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,ScAIRy stuff. ☠️,415859364,415859364,,,Nike
7,[],1180470652513525760,1570286908000,2019-10-05 10:48:28,2,,[],19,1180494973936029696,https://twitter.com/Nike/status/11804949739360...,Nike,,1,0,0,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,It's always better running with friends! 🐶🐶,415859364,415859364,,,Nike
8,[],1180224150641762306,1570227236000,2019-10-04 18:13:56,5,,[],04,1180244689036988416,https://twitter.com/Nike/status/11802446890369...,Nike,,2,1,0,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,Totally fine by us!,415859364,415859364,,,Nike
9,[],1179949602369196032,1570181428000,2019-10-04 05:30:28,6,,[],22,1180052556682321921,https://twitter.com/Nike/status/11800525566823...,Nike,,2,0,0,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,"We glad to hear you like this, Ryv. Get the be...",415859364,415859364,,,Nike
10,[],1179861310122725377,1570136388000,2019-10-03 16:59:48,3,,[],16,1179863645867708418,https://twitter.com/Nike/status/11798636458677...,Nike,,1,0,1,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,We 👀 you stepping up your game! Way to get aft...,415859364,415859364,,,Nike
11,[],1179785564595216385,1570119030000,2019-10-03 12:10:30,5,,[],18,1179790840727781376,https://twitter.com/Nike/status/11797908407277...,Nike,,1,0,0,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,"Hey Sharla, we have Master Trainers from acros...",415859364,415859364,,,Nike
12,[],1179711634501033986,1570109276000,2019-10-03 09:27:56,4,,[],21,1179749928937107457,https://twitter.com/Nike/status/11797499289371...,Nike,,4,1,0,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,😸,415859364,415859364,,,Nike
13,[],1179397500253478913,1570103607000,2019-10-03 07:53:27,2,,[],06,1179726150014242817,https://twitter.com/Nike/status/11797261500142...,Nike,,3,0,1,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,Great minds think alike. Couple goals. 👟 🔥,415859364,415859364,,,Nike
14,[],1179612461374345216,1570102106000,2019-10-03 07:28:26,5,,[],21,1179719857912328192,https://twitter.com/Nike/status/11797198579123...,Nike,,4,0,0,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,You got this in the 🎒. Let us know how the pro...,415859364,415859364,,,Nike
15,[],1179587422318931973,1570101647000,2019-10-03 07:20:47,7,,[],14,1179717929136345088,https://twitter.com/Nike/status/11797179291363...,Nike,,3,0,1,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,The motor on those motorcycles doesn't compare...,415859364,415859364,,,Nike
16,[],1179618359031169024,1570100036000,2019-10-03 06:53:56,2,,[],22,1179711173442375682,https://twitter.com/Nike/status/11797111734423...,Nike,,3,0,0,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,This much 🔥 should come with a warning: 'Might...,415859364,415859364,,,Nike
17,[],1179585545917390853,1570089269000,2019-10-03 03:54:29,4,,[],07,1179666014885289984,https://twitter.com/Nike/status/11796660148852...,Nike,,4,2,1,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,"Which one can you use to hang around, exercise...",415859364,415859364,,,Nike
18,[],1179440396503588864,1570035892000,2019-10-02 13:04:52,2,,[],13,1179442134627360769,https://twitter.com/Nike/status/11794421346273...,Nike,,5,1,0,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,👊,415859364,415859364,,,Nike
19,[],1179277970474708992,1570015020000,2019-10-02 07:17:00,5,,[],23,1179354590988374018,https://twitter.com/Nike/status/11793545909883...,Nike,,4,2,0,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,Those are spicy. Be careful not to burn the ha...,415859364,415859364,,,Nike
20,[],1179118341870501888,1569960808000,2019-10-01 16:13:28,1,,[],11,1179127211389001728,https://twitter.com/Nike/status/11791272113890...,Nike,,12,3,0,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,We'll see you on the pitch.💙😍,415859364,415859364,,,Nike
21,[],1178867438399700993,1569937796000,2019-10-01 09:49:56,1,,[],04,1179030689628512256,https://twitter.com/Nike/status/11790306896285...,Nike,,3,0,1,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,Breaking waves and strong runs. Looks like the...,415859364,415859364,,,Nike
22,[],1178916397776162816,1569916105000,2019-10-01 03:48:25,2,,[],02,1178939710133157890,https://twitter.com/Nike/status/11789397101331...,Nike,,1,1,0,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,Glad to hear you like'em. Keep tearing it up a...,415859364,415859364,,,Nike
23,[],1178220367548211200,1569794070000,2019-09-29 17:54:30,3,,[],16,1178427858924003328,https://twitter.com/Nike/status/11784278589240...,Nike,,12,2,2,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,Getting stronger every week. Nicely done! pic....,415859364,415859364,,,Nike
24,[],1177589551335968769,1569605850000,2019-09-27 13:37:30,2,,[],05,1177638407012540416,https://twitter.com/Nike/status/11776384070125...,Nike,,5,3,1,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,That colorway of the Zoom Freak 1 will release...,415859364,415859364,,,Nike
25,[],1177623326757400577,1569604734000,2019-09-27 13:18:54,3,,[],07,1177633727918350338,https://twitter.com/Nike/status/11776337279183...,Nike,,3,1,1,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,No better feeling. 💁‍♀️,415859364,415859364,,,Nike
26,[],1177562316365291520,1569604076000,2019-09-27 13:07:56,2,,[],16,1177630966573146114,https://twitter.com/Nike/status/11776309665731...,Nike,,4,0,0,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,Setbacks make for the greatest comebacks. Let'...,415859364,415859364,,,Nike
27,[],1177423529916227585,1569597062000,2019-09-27 11:11:02,5,,[],11,1177601546630160384,https://twitter.com/Nike/status/11776015466301...,Nike,,4,0,0,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,"For some it's exercise, for you it's a lifesty...",415859364,415859364,,,Nike
28,[],1177339488105897984,1569538800000,2019-09-26 19:00:00,3,,[],04,1177357181286572032,https://twitter.com/Nike/status/11773571812865...,Nike,,18,0,0,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,Bet.,415859364,415859364,,,Nike
29,[],1176867860175454209,1569422608000,2019-09-25 10:43:28,2,,[],07,1176869836128960512,https://twitter.com/Nike/status/11768698361289...,Nike,,2,0,0,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,No word on that colorway dropping. We can't gu...,415859364,415859364,,,Nike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35784,[],152859564809781248,1325281979000,2011-12-30 16:52:59,4,,[#makeitcount],15,152869816577961985,https://twitter.com/Nike/status/15286981657796...,Nike,,0,1,3,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,@mswendywei Here's to new beginnings! #makeitc...,415859364,415859364,,,Nike
35785,[],152851970988847106,1325281672000,2011-12-30 16:47:52,1,,[#makeitcount],01,152868530860212224,https://twitter.com/Nike/status/15286853086021...,Nike,,0,0,0,,,"[{'user_id': '415859364', 'username': 'Nike'}]",False,,,None,,EDT,@BigThumbsRus Do it up big! #makeitcount,415859364,415859364,,,Nike
35786,[],152850750136000512,1325281523000,2011-12-30 16:45:23,6,,[#makeitcount],08,152867905195876353,https://twitter.com/Nike/status/15286790519587...,Nike,,0,0,0,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,@AimeeKathrine So true! Happy new year and #ma...,415859364,415859364,,,Nike
35787,[],152804362803089408,1325280658000,2011-12-30 16:30:58,3,,[#makeitcount],08,152864276074344448,https://twitter.com/Nike/status/15286427607434...,Nike,,0,0,0,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,@leejasonl Graduation year is your year to set...,415859364,415859364,,,Nike
35788,[],152852831378997248,1325279717000,2011-12-30 16:15:17,6,,[#makeitcount],10,152860328726761472,https://twitter.com/Nike/status/15286032872676...,Nike,,0,0,0,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,@myTEAMTRIUMPHwi A noble & worthwhile cause. K...,415859364,415859364,,,Nike
35789,[],152853129656930306,1325278941000,2011-12-30 16:02:21,4,,[#makeitcount],11,152857075385503745,https://twitter.com/Nike/status/15285707538550...,Nike,,0,0,0,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,"@karleensmith It's all you! Make it happen, yo...",415859364,415859364,,,Nike
35790,[],152852056762355712,1325278837000,2011-12-30 16:00:37,3,,[#makeitcount],06,152856640016752640,https://twitter.com/Nike/status/15285664001675...,Nike,,0,1,0,,,"[{'user_id': '415859364', 'username': 'Nike'}]",False,,,None,,EDT,@Mandababineau Make every day count #makeitcount,415859364,415859364,,,Nike
35791,[],152852535391162368,1325278692000,2011-12-30 15:58:12,1,,[#makeitcount],14,152856031268048896,https://twitter.com/Nike/status/15285603126804...,Nike,,0,0,0,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,"@raypette Eye on the prize! Game time, all the...",415859364,415859364,,,Nike
35792,[],152568482272256000,1325278618000,2011-12-30 15:56:58,7,,[#makeitcount],17,152855719866150912,https://twitter.com/Nike/status/15285571986615...,Nike,,0,0,0,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,@omgvishal Good call. #makeitcount,415859364,415859364,,,Nike
35793,[],152848272942313474,1325278413000,2011-12-30 15:53:33,5,,[#makeitcount],08,152854862764322816,https://twitter.com/Nike/status/15285486276432...,Nike,,0,0,0,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,"@hilarym24 No regrets, no apologies. #makeitcount",415859364,415859364,,,Nike
35794,[],152812500314894337,1325277792000,2011-12-30 15:43:12,5,,[#makeitcount],04,152852254779645954,https://twitter.com/Nike/status/15285225477964...,Nike,,0,1,0,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,@karleensmith @RunDemCrew Which races will mak...,415859364,415859364,,,Nike
35795,[],152830864672309248,1325277576000,2011-12-30 15:39:36,2,,[#makeitcount],16,152851350227652608,https://twitter.com/Nike/status/15285135022765...,Nike,,0,0,0,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,"@meyola Consider adding ""Run"" to that list and...",415859364,415859364,,,Nike
35796,[],152502003577262081,1325277060000,2011-12-30 15:31:00,3,,[#makeitcount],16,152849184846905344,https://twitter.com/Nike/status/15284918484690...,Nike,,1,2,0,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,@rshoei Sleep is definitely key to staying hea...,415859364,415859364,,,Nike
35797,[],152803445940826113,1325276094000,2011-12-30 15:14:54,6,,[#makeitcount],12,152845133371547648,https://twitter.com/Nike/status/15284513337154...,Nike,,0,0,0,,,"[{'user_id': '415859364', 'username': 'Nike'}]",False,,,None,,EDT,"@RemingtonGuest Everyday, all day. #makeitcount",415859364,415859364,,,Nike
35798,[],152838464797286401,1325276008000,2011-12-30 15:13:28,5,,[#makeitcount],12,152844774779523073,https://twitter.com/Nike/status/15284477477952...,Nike,,0,0,1,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,@MelissaKosta Good call! You might want to che...,415859364,415859364,,,Nike
35799,[],152822000476372992,1325275428000,2011-12-30 15:03:48,5,,[#makeitcount],19,152842342729129984,https://twitter.com/Nike/status/15284234272912...,Nike,,0,0,0,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,@vincelavecchia A great mantra for 2012 #makei...,415859364,415859364,,,Nike
35800,[],152829870626447360,1325274649000,2011-12-30 14:50:49,3,,[#makeitcount],18,152839072124108800,https://twitter.com/Nike/status/15283907212410...,Nike,,0,0,0,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,@hilary4man Set your goal and we will help you...,415859364,415859364,,,Nike
35801,[],152821733638930432,1325274122000,2011-12-30 14:42:02,4,,[],16,152836862753521664,https://twitter.com/Nike/status/15283686275352...,Nike,,0,0,0,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,@nickonken Find the program that works for you...,415859364,415859364,,,Nike
35802,[],152833629012230145,1325273351000,2011-12-30 14:29:11,2,,[#makeitcount],18,152833629012230145,https://twitter.com/Nike/status/15283362901223...,Nike,,0,0,2,,,"[{'user_id': '415859364', 'username': 'Nike'}]",False,,,None,,EDT,@HollyMurray_ Turn your passion into action an...,415859364,415859364,,,Nike
35803,[],152811441072771072,1325273182000,2011-12-30 14:26:22,7,,[#makeitcount],19,152832920099356672,https://twitter.com/Nike/status/15283292009935...,Nike,,0,1,0,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,@pauljenkner 2012 is the year of your swing. Y...,415859364,415859364,,,Nike
35804,[],152780799966588928,1325273071000,2011-12-30 14:24:31,6,,[#makeitcount],12,152832456406466561,https://twitter.com/Nike/status/15283245640646...,Nike,,0,1,0,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,@CISN_Jack Don't wait until tomorrow to #makei...,415859364,415859364,,,Nike
35805,[],152781233036865536,1325272946000,2011-12-30 14:22:26,5,,[#makeitcount],01,152831929484447744,https://twitter.com/Nike/status/15283192948444...,Nike,,0,0,0,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,@MitchHero Tell us how you'll #makeitcount.,415859364,415859364,,,Nike
35806,[],152463180591935488,1325272709000,2011-12-30 14:18:29,2,,[#makeitcount],08,152830936659136512,https://twitter.com/Nike/status/15283093665913...,Nike,,0,0,1,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,@NanoTorres87 There is no finish line. #makeit...,415859364,415859364,,,Nike
35807,[],152809018698633216,1325272499000,2011-12-30 14:14:59,6,,[],21,152830055121289216,https://twitter.com/Nike/status/15283005512128...,Nike,,0,1,0,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,@PDXKHP Yoga counts.,415859364,415859364,,,Nike
35808,[],152824872370831360,1325272426000,2011-12-30 14:13:46,6,,[#makeitcount],01,152829749700468736,https://twitter.com/Nike/status/15282974970046...,Nike,,1,1,3,,,"[{'user_id': '415859364', 'username': 'Nike'}]",False,,,None,,EDT,"@NUMB1DJMIXFLY Work hard, train hard, and keep...",415859364,415859364,,,Nike
35809,[],152812087113023490,1325272387000,2011-12-30 14:13:07,5,,[#makeitcount],14,152829586701434880,https://twitter.com/Nike/status/15282958670143...,Nike,,0,0,0,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,"@briangstrong Ride to work, ride to the gym, r...",415859364,415859364,,,Nike
35810,[],152794119863943169,1325271876000,2011-12-30 14:04:36,6,,[#makeitcount],15,152827442040553472,https://twitter.com/Nike/status/15282744204055...,Nike,,0,0,0,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,"@Tylerdance1371 Every step, spin, and flare co...",415859364,415859364,,,Nike
35811,[],152822590057091072,1325271824000,2011-12-30 14:03:44,6,,[#makeitcount],01,152827225463463936,https://twitter.com/Nike/status/15282722546346...,Nike,,0,0,0,,,"[{'user_id': '415859364', 'username': 'Nike'},...",False,,,None,,EDT,@keyinfluencer Sounds like an amazing year. Do...,415859364,415859364,,,Nike
35812,[],152807634418941954,1325267153000,2011-12-30 12:45:53,7,,[#makeitcount],23,152807634418941954,https://twitter.com/Nike/status/15280763441894...,Nike,,117,137,903,,,"[{'user_id': '415859364', 'username': 'Nike'}]",False,,,None,,EDT,How will you #makeitcount in 2012? http://gon...,415859364,415859364,,,Nike
35813,[],152438645486395392,1325179179000,2011-12-29 12:19:39,4,,[],19,152438645486395392,https://twitter.com/Nike/status/15243864548639...,Nike,,202,30,1457,,,"[{'user_id': '415859364', 'username': 'Nike'}]",False,,,None,,EDT,"If You Have A Body, You Are An Athlete. -Bill ...",415859364,415859364,,,Nike

In [19]:
df_nike.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35814 entries, 0 to 35813
Data columns (total 30 columns):
cashtags           35814 non-null object
conversation_id    35814 non-null object
created_at         35814 non-null int64
date               35814 non-null object
day                35814 non-null int64
geo                35814 non-null object
hashtags           35814 non-null object
hour               35814 non-null object
id                 35814 non-null object
link               35814 non-null object
name               35814 non-null object
near               35814 non-null object
nlikes             35814 non-null int64
nreplies           35814 non-null int64
nretweets          35814 non-null int64
place              35814 non-null object
quote_url          35814 non-null object
reply_to           35814 non-null object
retweet            35814 non-null bool
retweet_date       35814 non-null object
retweet_id         35814 non-null object
search             35814 non-null object
source             35814 non-null object
timezone           35814 non-null object
tweet              35814 non-null object
user_id            35814 non-null int64
user_id_str        35814 non-null object
user_rt            35814 non-null object
user_rt_id         35814 non-null object
username           35814 non-null object
dtypes: bool(1), int64(6), object(23)
memory usage: 8.0+ MB

In [20]:
hashtags = []
for hashtag in df_nike['hashtags'].values.tolist():
    if len(hashtag) != 0:
        hashtags.extend(hashtag)

In [21]:
hashtags_dict = {x: hashtags.count(x) for x in hashtags}

In [22]:
nike_tag_count = pd.DataFrame.from_dict(hashtags_dict, orient='index', columns=['tag_count'])

In [23]:
nike_tag_count = nike_tag_count.sort_values(by=['tag_count'], ascending=False)

In [24]:
nike_tag_count

                      tag_count
#justdoit                  7229
#nikemag                   1033
#findgreatness             1014
#makeitcount                594
#counts                     512
#gameonworld                147
#usopenofsurf                68
#encuentratugrandeza         61
#fuelcheck                   60
#playrussian                 57
#innovate                    42
#breaking2                   31
#airmax                      22
#airmaxday                   18
#encontresuagrandeza         16
#fastisfaster                13
#runfree                     11
#sxsw                        11
#getouthere                  10
#keepup                      10
#riseasone                   10
#kobesystem                   9
#takeontj                     9
#kentucky                     8
#nikeplus                     8
#nikefuel                     8
#runnwm                       7
#wbf                          6
#maketherules                 6
#nike                         5
...                         ...
#ownchicago                   1
#fuelshawn                    1
#thechance                    1
#run75crew                    1
#wind                         1
#findgreatnesss               1
#letsgo                       1
#graviteam                    1
#pogojumps                    1
#tokubetsu                    1
#hyperdunk                    1
#worldseries                  1
#gs2squad                     1
#freeflyknits                 1
#countonkobeid                1
#freeflyknit                  1
#witnesshistory               1
#theshirt                     1
#thelegendgrows               1
#letsturnitup                 1
#believeit                    1
#lina                         1
#dontblink                    1
#probowl                      1
#bemecurial                   1
#hockeyisours                 1
#keepitcoming                 1
#boknows                      1
#grandeza                     1
#2011in4words                 1

[193 rows x 1 columns]

In [25]:
# df_nike_best = pd.read_pickle("./Pickles/df_best_nike_tweets.pkl")

In [26]:
# df_nike_best

In [27]:
# df_nike_best.groupby(df_nike_best['search'])[['tweet']].count()

In [28]:
df_300_nike_tweets = pd.read_pickle("./Pickles/df_300_nike_tweets.pkl")

In [29]:
df_300_nike_tweets.head()

,cashtags,conversation_id,created_at,date,day,geo,hashtags,hour,id,link,name,near,nlikes,nreplies,nretweets,place,quote_url,reply_to,retweet,retweet_date,retweet_id,search,source,timezone,tweet,user_id,user_id_str,user_rt,user_rt_id,username
0,[],1184117461093945344,1571150577000,2019-10-15 10:42:57,2,,[],23,1184117461093945344,https://twitter.com/KicksFinder/status/1184117...,KicksFinder,,12,0,9,,,"[{'user_id': '1703138106', 'username': 'KicksF...",False,,,Nike Air Max 270,,EDT,Ad: NEW Nike Air Max 270 Bowfin colorways are ...,1703138106,1703138106,,,KicksFinder
1,[],1184105285100675072,1571147674000,2019-10-15 09:54:34,4,,[],09,1184105285100675072,https://twitter.com/soldsoles/status/118410528...,soldsoles,,0,0,0,,,"[{'user_id': '4728024803', 'username': 'soldso...",False,,,Nike Air Max 270,,EDT,The Nike Air Max React 270 Triple Black online...,4728024803,4728024803,,,soldsoles
2,[],1184104560064958464,1571147501000,2019-10-15 09:51:41,2,,[],09,1184104560064958464,https://twitter.com/m88855771832/status/118410...,supker,,0,0,0,,,"[{'user_id': '707847179247849472', 'username':...",False,,,Nike Air Max 270,,EDT,Nike Air Max 270 React “Script Swoosh” Coming ...,707847179247849472,707847179247849472,,,m88855771832
3,[],1184103936858427392,1571147352000,2019-10-15 09:49:12,7,,[],16,1184103936858427392,https://twitter.com/RT_Kicks4Sale/status/11841...,Retweet Kicks4Sale,,0,0,0,,,"[{'user_id': '3150353906', 'username': 'RT_Kic...",False,,,Nike Air Max 270,,EDT,Nike Air Max 270 React “Script Swoosh” Coming ...,3150353906,3150353906,,,RT_Kicks4Sale
4,[],1184103671728095232,1571147289000,2019-10-15 09:48:09,6,,[#sneakerbar],22,1184103671728095232,https://twitter.com/Kickz2fire/status/11841036...,Kickz2Fire,,0,0,0,,,"[{'user_id': '2345620621', 'username': 'Kickz2...",False,,,Nike Air Max 270,,EDT,#SneakerBar Nike Air Max 270 React “Script Swo...,2345620621,2345620621,,,Kickz2fire

In [30]:
df_184_nike_tweets = pd.read_pickle("./Pickles/df_184_nike_tweets.pkl")

In [31]:
df_184_nike_tweets.head()

,cashtags,conversation_id,created_at,date,day,geo,hashtags,hour,id,link,name,near,nlikes,nreplies,nretweets,place,quote_url,reply_to,retweet,retweet_date,retweet_id,search,source,timezone,tweet,user_id,user_id_str,user_rt,user_rt_id,username
0,[],1176242192488259586,1569272966000,2019-09-23 17:09:26,6,,[],09,1176242192488259586,https://twitter.com/nicktiffany95/status/11762...,Nick Tiffany,,0,0,0,,,"[{'user_id': '147132016', 'username': 'nicktif...",False,,,Off-White x Nike Air Max 97,,EDT,Off-White x Nike Blazer Mid “Queen” Size 10.5 ...,147132016,147132016,,,nicktiffany95
1,[],1173046351606820864,1568511019000,2019-09-14 21:30:19,7,,[],12,1173046351606820864,https://twitter.com/BookwithB/status/117304635...,Bianca,,0,0,0,,,"[{'user_id': '1008418390401323008', 'username'...",False,,,Off-White x Nike Air Max 97,,EDT,OFF-WHITE x NIKE Air Max 97 190$ includes shi...,1008418390401323008,1008418390401323008,,,BookwithB
2,[],1172592573124268032,1568402829000,2019-09-13 15:27:09,1,,"[#nike, #offwhite, #theten]",08,1172592573124268032,https://twitter.com/Octoberxxxi/status/1172592...,October,,2,0,0,,,"[{'user_id': '946090520', 'username': 'October...",False,,,Off-White x Nike Air Max 97,,EDT,Nike x Off-White Air Max 97 “Og” #Nike #Offwhi...,946090520,946090520,,,Octoberxxxi
3,[],1170492963538886656,1567902243000,2019-09-07 20:24:03,3,,[],11,1170492963538886656,https://twitter.com/luisdior_/status/117049296...,luis dior,,0,1,0,,,"[{'user_id': '1151365512670040064', 'username'...",False,,,Off-White x Nike Air Max 97,,EDT,"Air Jordan 1 UNC x Off-White, Nike Air Max 97 ...",1151365512670040064,1151365512670040064,,,luisdior_
4,[],1170120053590806528,1567813565000,2019-09-06 19:46:05,6,,[],03,1170121018331029516,https://twitter.com/TheAgera/status/1170121018...,Agera,,1,1,0,,,"[{'user_id': '460852750', 'username': 'TheAger...",False,,,Off-White x Nike Air Max 97,,EDT,In order of purchase - Adidas Goretex NMD Nike...,460852750,460852750,,,TheAgera